academy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
]

account/urls.py
from django.urls import path
from .views import register_user, login_user, logout_user

app_name = 'account'

urlpatterns = [
    path('registration/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

main/urls.py
from django.urls import path
from .views import (
    index,
    academy_view,
    create_manager_view,
    update_manager_view,
    delete_manager_view,
    create_mentor_view,
    update_mentor_view,
    delete_mentor_view,
    create_student_view,
    update_student_view,
    delete_student_view

)

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),

    # academy
    path('academy/<int:pk>/', academy_view, name='academy'),

    # managers
    path('create_manager/', create_manager_view, name='create_manager'),
    path('update_manager/<int:pk>/', update_manager_view, name='update_manager'),
    path('delete_manager/<int:pk>/', delete_manager_view, name='delete_manager'),

    # mentors
    path('create_mentor/', create_mentor_view, name='create_mentor'),
    path('update_mentor/<int:pk>/', update_mentor_view, name='update_mentor'),
    path('delete_mentor/<int:pk>/', delete_mentor_view, name='delete_mentor'),

    # students
    path('create_student/', create_student_view, name='create_student'),
    path('update_student/<int:pk>/', update_student_view, name='update_student'),
    path('delete_student/<int:pk>/', delete_student_view, name='delete_student'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
<div class="Header">
    {% block Header %}
    <h1>Header</h1>
    <a href="{% url 'account:logout' %}"><button>Logout</button></a>
    {% endblock Header %}

</div>

<div class="Menu">
    {% block Menu %}
    <h1>Menu</h1>
    <div class="navbar">
        <div class="dropdown">
            <button class="dropbtn"> Manager
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'main:create_manager' %}">Manager кошуу</a>
                {% for manager in manager %}
                <a href="{% url 'main:manager' manager.id %}">{{manager.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"> Mentor
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'main:create_mentor' %}">Mentor кошуу</a>
                {% for mentor in mentors %}
                <a href="{% url 'main:mentors' mentor.id %}">{{mentor.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"> Student
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'main:create_student' %}">Student кошуу</a>
                {% for student in students %}
                <a href="{% url 'main:students' student.id %}">{{student.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}
</div>

<div class="Content">
    {% block Content %}
    {% endblock Content %}
</div>

<div class="Footer">
    {% block Footer %}
    <h1>Footer</h1>
    {% endblock Footer %}
</div>
</body>
</html>